### ISSUE TITLE
homebank: language files are installed in the wrong dir

### ISSUE THREAD

**Issue by Kdecherf** [Kdecherf/kdecherf-exheres#3]
Language files of package homebank uses incorrect prefix during installation. This leads to inability to detect available languages.

**Comment by avrelaun** [comment]
I still can't use homebank on exherbo for this reason.
We could work together on this if you want.

**Comment by Kdecherf** [comment]
Oh well I missed that, sorry. Will work today on this.

**Comment by Kdecherf** [comment]
Note: LC_MESSAGES must be empty for Homebank to use its internal language preference.
